### ISSUE TITLE
Identd on El Capitan

### ISSUE THREAD

**Issue by uhlhosting** [alexbarton/homebrew-alex#1]
KosmicX:~ kosmos$ brew tap alexbarton/homebrew-alex
==> Tapping alexbarton/alex
Cloning into '/usr/local/Library/Taps/alexbarton/homebrew-alex'...
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 13 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
Checking connectivity... done.
Tapped 6 formulae (43 files, 209.6K)
KosmicX:~ kosmos$ brew search identd
alexbarton/alex/identd
Error: GitHub API rate limit exceeded for 89.173.27.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 51 minutes 10 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: HOMEBREW_GITHUB_API_TOKEN
KosmicX:~ kosmos$ brew install identd
==> Installing identd from alexbarton/alex
==> Cloning http://rc.shaunrowland.com/git/identd.git
Cloning into '/Library/Caches/Homebrew/identd--git'...
Checking connectivity... done.
==> Checking out branch master
==> Patching
patching file identd/identd.8
Hunk #1 succeeded at 32 with fuzz 2.
==> xcodebuild -target identd -configuration Release
Last 15 lines from /Users/kosmos/Library/Logs/Homebrew/identd/01.xcodebuild:

xcodebuild -target identd -configuration Release

2016-01-14 21:23:55.357 xcodebuild[24571:808671] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
=== BUILD TARGET identd OF PROJECT identd WITH CONFIGURATION Release ===

Check dependencies
error: There is no SDK with the name or path '/tmp/identd20160114-24538-1gmo8zd/macosx10.7'

*\* BUILD FAILED **

The following build commands failed:
    Check dependencies
(1 failure)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/alexbarton/homebrew-alex/issues

KosmicX:~ kosmos$

**Comment by alexbarton** [comment]
Thanks for reporting this problem @highacid!

**Comment by uhlhosting** [comment]
Sure no problem, just let me know when this is working, also a fork for oidentd would be great since it has.

**Comment by alexbarton** [comment]
@highacid: I closed this issue because I think the problem is resolved already.

Just running `brew update && brew install alexbarton/alex/identd` should do the trick – no?

**Comment by uhlhosting** [comment]
@alexbarton 

KosmicX:~ kosmos$ brew update && brew install alexbarton/alex/identd
Updated Homebrew from a08011e to 1fd767b.

Updated 1 tap (alexbarton/alex).
==> New Formulae
alexbarton/alex/droopy                                                          onioncat                                                                        truncate
==> Updated Formulae
ansible                       freediameter                  keybase                       lsh                           nsq                           pure-ftpd                     swiftlint                     vte3 ✔
awscli                        fzf                           knot                          mailhog                       ntopng                        pyenv-virtualenv              syncthing-inotify             weechat
bitlbee                       gauge                         kubernetes-cli                mailutils                     openconnect                   qemu                          task                          wireshark
corectl                       gedit                         libinfinity                   megacmd                       opus                          rdfind                        taskd                         xapian
cryptopp                      git-annex                     librevenge                    minbif                        pandoc                        rdup                          telegraf                      youtube-dl
dcd                           glib-networking ✔             libsoup                       monetdb                       pianobar                      saldl                         ucommon                       zabbix
devd                          gnu-smalltalk                 libsvm                        ncdc                          pianod                        selenium-server-standalone    upscaledb
dfmt                          gnutls ✔                      libvirt ✔                     nettle ✔                      pidgin                        sift                          v8
elixir                        gwenhywfar                    lighttpd                      ngrok                         pike                          skinny                        vim
ffmpeg                        htmldoc                       loudmouth                     node                          profanity                     stoken                        vpnc
==> Installing identd from alexbarton/alex
==> Cloning http://rc.shaunrowland.com/git/identd.git
Updating /Library/Caches/Homebrew/identd--git
==> Checking out branch master
==> Patching
patching file identd/identd.8
Hunk #1 succeeded at 32 with fuzz 2.
(Stripping trailing CRs from patch.)
patching file identd.xcodeproj/project.pbxproj
==> xcodebuild SYMROOT=build -target identd -configuration Release
🍺  /usr/local/Cellar/identd/0.20120228: 3 files, 84.2K, built in 4 seconds
KosmicX:~ kosmos$
KosmicX:~ kosmos$

**Comment by alexbarton** [comment]
Thanks for testing, seems to work :+1:

**Comment by uhlhosting** [comment]
Hi Alex, indeed it works to install it, yet I cannot locate in my mac the identd.conf . any idea where this could be? And I am using it on undernet network, and my account does not seem to have it running according to this:

311: HIM ~HIM cosmicsounds.users.undernet.org \* Ancient
319: HIM #undernet #helpless #Phat #linux 
312: HIM amsterdam.nl.eu.undernet.org Undernet IRC server
330: HIM cosmicsounds is logged in as
338: HIM ~HIM@static-dsl-158.87-197-154.telecom.sk 87.197.154.158 Actual user@host, Actual IP
317: HIM 459 1453126359 seconds idle, signon time
318: HIM End of /WHOIS list.

**Comment by alexbarton** [comment]
Configuration file is `/usr/local/etc/identd.user`, see `man identd`, but there is none by default.

And probably your internet router does NAT, so the IRC server can't reach your Mac on the Ident port (113) anyway?
